//
//  TangramElementFactoryProtocol.h
//  Tangram
//
//  Created by xiaoxia on 2017/1/9.
//
//

#import <Foundation/Foundation.h>
#import "TangramItemModelProtocol.h"
@protocol TangramElementFactoryProtocol <NSObject>

@required



/**
 Return view by model

 @param model ItemModel Generated by ItemModelFactoty
 @return view
 */
+ (UIView *)elementByModel:(NSObject<TangramItemModelProtocol> *)model;

/**
 Return view after be refreshed

 @param  element to be refreshed
 @param  model
 @return element after refreshed
 */
+ (UIView *)refreshElement:(UIView *)element byModel:(NSObject<TangramItemModelProtocol> *)model;

@end
